try {
    alert('Begin try runs')
    alert('end try runs')
}catch(err){
    alert('catch is ignored there are no errors')
}